image: node

definitions:
  steps:
    - step: &lint
        name: Lint
        script:
          - npm install eslint
          - npm install eslint-plugin-promise
          - npx eslint **/*.ts[x]
    - step: &build
        name: Build
        script:
          - npm install
          - echo > ".env"
          - echo REACT_APP_GOOGLE_API_KEY=$GOOGLE_API_KEY >> ".env"
          - echo REACT_APP_HANDSHAKE_API_KEY=$HANDSHAKE_API_KEY >> ".env"
          - npm run build
        artifacts:
          - build/**
    - step: &deploy
        name: Deploy
        deployment: production
        script:
          - cd functions
          - npm install
          - cd ..
          - pipe: atlassian/firebase-deploy:1.0.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT

pipelines:
  pull-requests:
    "**":
      - step: *lint
      - step: *build

  branches:
    master:
      - step: *lint
      - step: *build
      - step: *deploy
