image: node

definitions:
  steps:
    - step: &setup
        name: Set up environment
        script:
          - echo > ".env"
          - echo REACT_APP_GOOGLE_API_KEY=$GOOGLE_API_KEY >> ".env"
          - echo REACT_APP_HANDSHAKE_API_KEY=$HANDSHAKE_API_KEY >> ".env"
    - step: &test
        name: Run unit tests
        script:
          - npm install
          - npm run test
        caches:
          - node
    - step: &lint
        name: Check code style
        script:
          - npm install
          - npx eslint **/*.ts[x]
        caches:
          - node
    - step: &build
        name: Build application
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
        caches:
          - node
    - step: &deploy
        name: Deploy to Firebase
        script:
          - cd functions
          - npm install
          - cd ..
          - pipe: atlassian/firebase-deploy:1.0.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT

pipelines:
  pull-requests:
    "**":
      - step: *setup
      - step: *test
      - step: *lint
      - step: *build

  branches:
    master:
      - step: *lint
      - step: *build
      - step: *deploy
