image: node

definitions:
  steps:
    - step: &lint
        name: Lint
        script:
          - npm install eslint
          - npm install eslint-plugin-promise
          - npx eslint --fix src/**/*.ts[x]
        caches:
          - node
    - step: &build
        name: Build
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
    - step: &deploy
        name: Deploy to Firebase
        script:
          - cd functions
          - npm install
          - cd ..
          - pipe: atlassian/firebase-deploy:1.0.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT

pipelines:
  pull-requests:
    "**":
      - step: *lint
      - step: *build

  branches:
    master:
      - step: *lint
      - step: *build
      - step: *deploy
